name: Run Postman Collection from SQLite

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create output directory
      run: mkdir -p output

    - name: Run SQLite-powered Postman test
      run: node scripts/runFromSqlite.js

    - name: Upload Newman Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: postman-report
        path: output/report.json
